version: '2.1'
# ELK stack designed for container-native deployment
services:
# ---------------------------------------------------
# The Kibana application queries the ES cluster
nginx:
	image: autopilotpattern/nginx:test
	mem_limit: 128m
	restart: always
	environment:
		- CONSUL_AGENT=1
		- CONSUL=elk-consul.svc.${TRITON_CNS_SEARCH_DOMAIN_PRIVATE}
	ports:
		- 80
		- 443
		- 9090
	labels:
		- triton.cns.services=elk-kb
	network_mode: bridge
# ---------------------------------------------------
# The Kibana application queries the ES cluster
  kb:
    image: autopilotpattern/kibana:test
    mem_limit: 2g
    restart: always
    ports:
      - 5601 # default Kibana port
    network_mode: bridge
    environment:
      - CONSUL_AGENT=1
      - CONSUL=elk-consul.svc.${TRITON_CNS_SEARCH_DOMAIN_PRIVATE}
      - CONFIG_PATH=/usr/share/kibana/config/kibana.yml
      - NODE_ENV=production
      - CONTAINERPILOT=/etc/containerpilot.json5
    command: >
      /usr/local/bin/containerpilot

# ---------------------------------------------------
# The logstash container is the target of Docker log drivers
  ls:
    image: autopilotpattern/logstash:test
    mem_limit: 2g
    restart: always
    labels:
      - triton.cns.services=elk-ls
    ports:
    # because the ports are chosen by the log_driver config
    # these are fairly arbitrary but we're keeping them at
    # the typical non-container values for familiarity
    - "514"       # syslog tcp port
    - "514/udp"   # syslog udp port
    - "12201"     # gelf
    - "12201/udp" # gelf udp port
    # - "24224"     # fluentd tcp port
    network_mode: bridge
    environment:
      - CONSUL_AGENT=1
      - CONTAINERPILOT=/etc/containerpilot.json5
      - CONSUL=elk-consul.svc.${TRITON_CNS_SEARCH_DOMAIN_PRIVATE}
    command: >
      /usr/local/bin/containerpilot

# ---------------------------------------------------
# The fabio container is the http load balancer in front of kibana
  fabio:
    image: autopilotpattern/fabio:test
    mem_limit: 2g
    restart: always
    ports:
      - 80
      - 9998
    network_mode: bridge
    environment:
      - CONSUL_AGENT=1
      - CONTAINERPILOT=/etc/containerpilot.json5
      - CONSUL=elk-consul.svc.${TRITON_CNS_SEARCH_DOMAIN_PRIVATE}
    command: >
      /usr/local/bin/containerpilot

# ---------------------------------------------------
# This common service definition is the default for nodes that both store
# data and act as potential masternodes. It also serves as a template for
# master-only and data-only ES nodes.
  es:
    image: autopilotpattern/elasticsearch:test
    mem_limit: 4g
    restart: always
    labels:
      - triton.cns.services=elk-es-master
    network_mode: bridge
    environment:
      - ES_SERVICE_NAME=elasticsearch-master
      - CLUSTER_NAME=elasticsearch
      - ES_NODE_MASTER=true # default
      - ES_NODE_DATA=true   # default
      - CONSUL_AGENT=1
      - CONSUL=elk-consul.svc.${TRITON_CNS_SEARCH_DOMAIN_PRIVATE}
      # set the number of threads we want based on the number of CPU shares
      # that we'll get for this size container on Triton
      - ES_JAVA_OPTS=-Xms1g -Xmx1g -XX:-UseGCTaskAffinity -XX:-BindGCTaskThreadsToCPUs -XX:ParallelGCThreads=1 -XX:ParallelCMSThreads=1
    command: >
      /usr/local/bin/containerpilot

  # ---------------------------------------------------
  # The master-only node serves as the coordinator of the cluster only

  es_master:
    extends:
      service: es
    labels:
      - triton.cns.services=elk-es-master
    environment:
      - ES_SERVICE_NAME=elasticsearch-master
      - ES_NODE_MASTER=true
      - ES_NODE_DATA=false

  # ---------------------------------------------------
  # Data-only nodes never act as master nodes.

  es_data:
    extends:
      service: es
    labels:
      - triton.cns.services=elk-es-data
    environment:
      - ES_SERVICE_NAME=elasticsearch-data
      - ES_NODE_MASTER=false
      - ES_NODE_DATA=true

  # ---------------------------------------------------
  # Consul as a service discovery tier
  consul:
    image: autopilotpattern/consul:${TAG:-latest}
    labels:
      - triton.cns.services=elk-consul
      - com.joyent.package=dds-128m
    restart: always
    mem_limit: 128m
    ports:
      - 8500
    network_mode: bridge
    environment:
      - CONSUL=elk-consul.svc.${TRITON_CNS_SEARCH_DOMAIN_PRIVATE}
    command: >
      /usr/local/bin/containerpilot
